### ISSUE TITLE
Japan Buffs

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#11]
->Event for 1. jan 1836
add Buff "The path of Westernization":
provides the following buffs for 10 years:
+10% chance for enacting laws
+10% education access 
+30% uni throughput

changes IG leader of Shogunate IG to jingoist ideology

gives perma claims on: 
Korea: Yeongnam, Yangho, Gyeonggi, Yangseo, Gwanbuk
Qing: Shengjing, Formosa

->Better Meji restoration buffs:
Grants Buff "Empire of the rising Sun"

add the following buffs for 15 years:
+35% tech spread
-10% infamy generation
+15% infamy decay
+30% Off / Def Army & Navy 

perma claims on: 
Option1:
Siam: Nakhon Ratchasima, Laos, Tenasserim
Java: West Java, Central Java, East Java

Option2:
Borneo: East Borneo, West Borneo, North Borneo
Dai nam:  Tonkin, Annam, Mekong, Cambodia

**Comment by MasterSon-git** [comment]
@xEiweix if je meiji restauration completes "Emperor takes power" (first event in chain)

-> immediately activate buff "Empire of the rising Sun"
-> Option 1 "favour the industrialists" -> add claims Siam/Java
-> Option 2 "favour the intellectuals" -> add claims Borneo/DaiNam

right?

**Comment by MasterSon-git** [comment]
so two new events implemented
-> Event "The path of Westernization" trigger after 7 days ingame
-> Event "Empire of the rising Sun" triggers 7 days after all Meiji Reforms are completed

Event 1 enables/disables following events and it's not available for the AI
