### ISSUE TITLE
Add mod "Gas, Guns, Garb&Grub"

### ISSUE THREAD

**Issue by MasterSon-git** [MasterSon-git/vic3-kmpmp#13]
https://steamcommunity.com/sharedfiles/filedetails/?id=2968644620
 - navy bases:
 - delete uniforms PM
 - delete rations PM
 - check compatibility with "All quiet on the western front" -> espacially barracks

 - barrack:
 - rations (lila production method wie medical aid)
 - letzte PM ändern (statt der mit Strom) auf:  
   abundand rations: Goods: 1 Food, 1fruit, 1Liquor,   +10% Moral recovery
   zusätzliche PM
   luxery rations: 1.5 Food, 1 Coffee, 1 Tea, 1 Liquor,  +20% Moral recovery

 - barracks:
  - clothing: (lila methode wie medical aid)
  - No Uniforms: +10% Moral loss, -5 Offense, Goods req: no goods
  - traditional garb: no effects, Goods: 0.5 Clothes
  - Full Dress:  5 offense, 5 defense, Goods:  1 Cloth 
  - Full Elite Dress: 5 offense, 5 defence, -2 Morale loss, Goods:  1 Luxery Cloth
  - Helmets & Darb: 10 offense, 10 Defense, 10% recovery rate, Goods: 0.2 steel  1 Cloth
  - Elite Helmets & Darb: 10 offense, 10 Defense, 10% recovery rate, -2 moral loss, Goods: 0.4 Steel 1 Luxery cloth

  - baracks: 
  - infantry equipment: (secondary equipment adjustment)
  - Primitive weapons: -10 Offense -10 Defence, Good: None
  - Handguns: None, Good: 0.5 small arms
  - Muskets: 10 Off 10 def 2% Kill rate, Goods: 1.0 small arms 
  - Rifles:  15 Off 10 Def, Goods: 1 small arms  1.0 Ammunition 3% Kill rate (needs riflling tech)
  - Repeating Rifles: 25 Off 25 Def 5% Kill rate, Goods: 1,5 small arms 2 Ammunition (needs repeaters tech)
  - Bolt Action Rifles: 30 Off 30 Def. 7% kill rate, Goods: 2 small arms 3 Ammunition (Needs bolt action rifle tech)
  - Semi automatic Rifles: Goods: 35 Off, 35 Def 9% killrate, Goods: 3 small arms 3.5 Ammunition (needs automatic maschine gun tech)

**Comment by MasterSon-git** [comment]
@xeiweix should i remove changes to navy pm which adds coal and oil usage?

changes are listed here:
https://steamcommunity.com/workshop/filedetails/discussion/2968644620/3827539750718888858/

**Comment by xEiweix** [comment]
nope thats a change i want to use
