### ISSUE TITLE
Buff Bolivia

### ISSUE THREAD

**Issue by MasterSon-git** [MasterSon-git/vic3-kmpmp#130]
Antofagasta
- 10x pops
-

**Comment by xEiweix** [comment]
change starting infamy 50 -> 20


Antofagasta:
pops x10
add 30 coal mines
add 25 arable land
add 5 fishing wharfs

La paz:
+50% pops

**Comment by MasterSon-git** [comment]
Antofagasta: arable land to 60 to prevent unemployed pops
