### ISSUE TITLE
New Companies / changes (WIP kommt Montag)

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#138]
### Unique Companies:

**Great Rubber Corporation of Indochina (NEW)**
Req:
->owns malaya
->5 Rubber Plant in Malaya

effected buildings:
-> Rubber Plant

Prosperity Buff:
+5% Electric Industries TP
+5% Trade Center TP
_____

**G. Ricordi & C.** (Italy/Lombardy)
add 10% Sulfur Mines TP

________

**Taiwanese Tee Company:**
Req:
10 Tea plantations in Formosa

effects: 
Tea Plantations

Prosperity Buff:
-20% consumption tax costs
+10% Motor industries TP
_______

**Imperial Tobacco Corporation of Persia  (Change)**
-> change Name Imperial Dye Corporation of Persia

Prosperity Buff:
-> change Techspread 15% > 10%
-> change Infra 10% -> 15%

### Basic Companies:

**Basic Motors:** (change)
Prosperity Buff:
add 10% steel mill TP
add 10% Oil riggs TP

______

**Basic Arts:**
Req:
5 Arts Academies in one state

effects: 
Art academy

Prosperity Buff:
10% Power Plants TP
10% Tool shop TP

____

**Comment by Tziplays** [comment]
Atlanis Arts academy !

**Comment by Yukinu** [comment]
Companys are created but the illus are not done
