### ISSUE TITLE
UI Military Mobilization Options

### ISSUE THREAD

**Issue by MasterSon-git** [MasterSon-git/vic3-kmpmp#168]
Allow Expand/Collapse military mobilization options per army

**Comment by Yukinu** [comment]
Hatte ich mit Eiwei schon mal drüber gesprochen, dafür muss du die komplette GUI in dem Bereich reworken und diese dann bei jedem Change die Paradox in Zukunft in dem Menu macht, anpassen.

**Comment by MasterSon-git** [comment]
Solved with #182

**Comment by MasterSon-git** [comment]
@Yukinu da wir in der Datei sowieso Anpssungen wegen den vielen Mobilisierungsoptionen haben, hab ich das dort jetzt mit eingebaut.
