### ISSUE TITLE
Change decree "Public Health Program"

### ISSUE THREAD

**Issue by MasterSon-git** [MasterSon-git/vic3-kmpmp#17]
change +8% birthrate for accepted pops to primary culture

**Comment by MasterSon-git** [comment]
seems like pops of a state cant have modifiers... so i think we need to calculate amount of pops of primary culture and add them to state_birth_rate_mult ... maybe... might work with "scipted_modifier"

**Comment by xEiweix** [comment]
warum funktioniert dann eigentlich accepted pops birthrate?

**Comment by MasterSon-git** [comment]
weil es dafür nen modifier direkt vom spiel gibt.... hab das thema jetzt auch im discord von der Vi3 Mod Community aufgemacht. Die sagen das geht nicht... mal gucken ich hab noch eine idee

**Comment by MasterSon-git** [comment]
ist nicht weil geht nicht...^^ in create_pop culture can't be variable and its impossible to count pop of state by culture

**Comment by xEiweix** [comment]
rip dann überleg ich mir was
