### ISSUE TITLE
Changes based on mp tests

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#18]
Barracks PMS:
line inf: 1 small
 arms
Skrimish inf: 1 small arms
Trench inf: 1small arms 1 Ammo
Squad inf: 1small arms 1.5 Ammo
Mech inf: 1 small arms  2 Ammo

Secondary PM:
Infantry eq:   muskets 5 Off 5 Def 2% killrate

Edict:
Health care:
5% Birth rate
5% Birthrate accepted pops
-5% Mortality

Greener Gras:
Migration attraction 50->75%
+1 SOL

**Comment by MasterSon-git** [comment]
@xEiweix there is no modifier for the calculated SOL of pops. but we can change expected SOL with a multiplier `state_expected_sol_mult` should i grant 10%?

**Comment by MasterSon-git** [comment]
@xEiweix ok nvm, blinde by the light^^ `state_standard_of_living_add`
