### ISSUE TITLE
Add functionality "No second naval invasion"

### ISSUE THREAD

**Issue by MasterSon-git** [MasterSon-git/vic3-kmpmp#20]
mod "No second naval invasion" is outdated and provides old context menues.

- add a custom functionality to prevent second naval invasions

**Comment by MasterSon-git** [comment]
actually reimplemented mod "No second naval invasion"
https://steamcommunity.com/sharedfiles/filedetails/?id=2980559841

but maybe i have better idea than disabling right_click menu items which starts naval invasions...

so, this issue is still todo

**Comment by Yukinu** [comment]
Hey, is this an open topic? i guess i saw some other point for "no second naval invasion" more on top of the tasks

**Comment by MasterSon-git** [comment]
just for the record #19 was the task which implements the mod
