### ISSUE TITLE
UI add Company Images

### ISSUE THREAD

**Issue by MasterSon-git** [MasterSon-git/vic3-kmpmp#238]
add images for
- company_basic_furniture
- company_imperial_porcelan_company
- company_heineken_international
- company_shell
- company_persian_luxury_goods

**Comment by Waysten** [comment]
company_Korean_Tungsten_Company
company_Imperial_Arsenal
company_Genda_Shigyo

**Comment by Yukinu** [comment]
Added graphics for:
Shell,
Persian_Luxury_Goods
genda_shigyo
imperial_arsenal_japan
korean_tungsten_company
heineken_international
imperial_porcelan_company
basic_furniture
