### ISSUE TITLE
German-French content

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#275]
**_PRUSSIA / NGF / GERMANY:_**
**JE: The Matter of the Reichsland**

condition:
year is before 1871:
NGF / Germany owns Alsace-Lorraine as state

grants:
 +5% of the germany's pops become loyalists
→ add buff “The Reichsland”
 -15% loan interest rate for 5 years
 +20% training rate for 1 year

**JE: the industrial heartland**

condition:
→ year is at least 1860
→ is NGF or Germany does not own Rhineland and Northrine as incorporated land

grants:
→ 8% of the north and south german pops become radical

add the buff “the industrial heartland is lost” 
-10% company construction bonus
-5% company throughput bonus

_______

**_FRANCE:_**
**JE: the border with the germans**
condition:
year is at least 1845
year is before 1871
France owns Alsace-Lorraine as incorporated state:

grants:
→add buff "historical border”
→ + 5 legitimacy
→ + 5% minting
→ + 1% pop growth for accepted pops

will fail if:
France does not own Alsace-Lorraine (loses buff for ever)

**JE: humiliated by the germans** 
conditions: 
→ France does not own Alsace-Lorrain as state for at least 7 years

grants:
→ France gets the buff “humiliated by the germans”
→ 3% tax waste
→ -3 Legitimacy
→ -1 approval of Armed forces

(restarts each time France loses that state)

**JE: Rhine borders**
Option 1: 
→ delete ursprünglichen buff
→ add buff “the natural borders”(perm buff as long as France holds the Rhineland and North Rhine as incorporated states, reaktivates when 
    ever that situation is the case after finishing Rhine Borders once)
+10% Army Def
+3% pop growth for accepted pops
+5 Legitimacy
→ add tooltip to make player aware of the conditon to retain that buff

Option 2: 
→ 15% of the frances pops (entire nation not just french pops) become loyalists
→ added buff “a victory for the masses” for 20 years
+25% influence 
-20% interest rate
+20% mandate progress
+20% loyalists from sol increase

Option 3:
→ added Allemanic as prime culture

**Comment by Waysten** [comment]
@xEiweix Vorraussetzungen fehlen für den letzten JE

**Comment by xEiweix** [comment]
> [@xEiweix](https://github.com/xEiweix) Vorraussetzungen fehlen für den letzten JE

vanilla
