### ISSUE TITLE
Add new mods

### ISSUE THREAD

**Issue by MasterSon-git** [MasterSon-git/vic3-kmpmp#287]
- GPD Plotline Plus: https://steamcommunity.com/sharedfiles/filedetails/?id=3190466673
- ~Break Truce: https://steamcommunity.com/sharedfiles/filedetails/?id=3168188451~
  - added in #270 
- ~Anbeeld Stockpile Mod: https://steamcommunity.com/sharedfiles/filedetails/?id=3249228964~
- Visible Shortage Fix: https://steamcommunity.com/sharedfiles/filedetails/?id=3273620528
- ~Trains give land trade: https://steamcommunity.com/sharedfiles/filedetails/?id=3192720245~
  - moved to #329

**Comment by xEiweix** [comment]
Anbeelds Stockpile lassen wir erstmal raus
