### ISSUE TITLE
New Navy PMs

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#3]
Navy Base:
Ironclad amor brauch ironclad tech. monitor monitor batterie monitor tech etc.

->Amor: (primary production adjustment) 

ManOwar Amor: no effect, no goods
 
Basic Ironclad Amor: +10 Def Goods: 0.5 Ironclads
Improved Ironclad Amor: +15 Def Goods: 1 Ironclads
Advanced Ironclad Amor: +20 Def Goods: 1.5 Ironclads

Basic Monitor Amor: +25 Def 2Ironclads
Improved Monitor Amor: +30 Def Goods: 2.5 Ironclads
Advanced Monitor Amor: +35 Def Goods: 3 Ironclads

Basic Dreadnought Amor: +40 Def Goods: 3.5 Ironclads
Improved Dreadnought Amor: +50 Def Goods: 4 Ironclads
Advanced Dreadnought Amor: +60 Def Goods: 4.5 Ironclads

Basic Battleship Amor: +70 Def Goods: 5 Ironclads
Improved Battleship Amor: +80 Def Goods: 5.5 Ironclads
Advanced Battleship Amor: +90 Def Goods: 6 Ironclads

->Batterie: (primary production adjustment)

ManOwar Batterie: no effect, no goods

Basic Ironclad Batterie: +10 Off Goods: 1 canons
Improved Ironclad Batterie: +15 Off Goods: 1.5 canons
Advanced Ironclad Batterie: +20 Off Goods: 2 canons

Basic MonitorBatterie: +25 Off Goods: 2.5 canons
Improved Monitor Batterie: +30 Off Goods: 3 canons
Advanced Monitor Batterie: +35 Off Goods: 3.5 canons

Basic Dreadnought Batterie: +40 Off Goods: 4 canons
Improved Dreadnought Batterie: +50 Off Goods: 4.5 canons
Advanced Dreadnought Batterie: +60 Off Goods: 5 canons

Basic Battleship Batterie: +70 Off Goods: 5.5 canons
Improved Battleship Batterie: +80 Off Goods: 6 canons
Advanced Battleship Batterie: +90 Off Goods: 6.5 canons

**Comment by MasterSon-git** [comment]
todo: add off to armor and def to batteries

defense does not protect from damage it's the attacking value for the defender...
