### ISSUE TITLE
Cultures and homelands (adapted version of what ludi mod did)

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#389]
merge most useless cultures to usefull ones to improve performance 
delete all homeland except the sokoto cultures in Africa
delete most homelands except natives in America
delete most useless homelands in South east Asia

dreamz is already working on that

**Comment by MasterSon-git** [comment]
rework state pops actually done from 00-03
TODO: 04-15

**Comment by MasterSon-git** [comment]
replaced with another issue
