### ISSUE TITLE
Check Japan tech events

### ISSUE THREAD

**Issue by MasterSon-git** [MasterSon-git/vic3-kmpmp#395]
- there are random events for Japan which should give 100% tech spread, it seems they are not applied - check this

**Comment by Waysten** [comment]
konnte keine Fehler im Code finden. Die Events haben die Richtigen modifier 
Es kann sein weil bei Japan extra es die mult. auf nur Branchen gibt das es daher kommt. Diese gelten aber nur für die jeweilige tec Branche (Prod/Mil/Soc)

![Image](https://github.com/user-attachments/assets/f5279050-4a6c-4e0a-b0ee-bfe18b6bb3a1)

**Comment by MasterSon-git** [comment]
@Waysten teste das event mal bitte - das kannst du über die Konsole ja einfach auslösen und dann schauen ob die Modifier für das Land korrekt angewendet werden
