### ISSUE TITLE
Block rebalance

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#399]
**Blockbuffs:**
Religious Convocation:
change conversion buff from 33% to 50%
add -5% mob good req

**general:**
remove negative leverage generation from wrong culture
nerf own leverage generation from pops by another 20%
increase leverage generation from economic dependence by 10%
finally fix the tooltips on mandates

**Mandates:**
def cooperation
add -5% military goods cost to lvl 3 Def cooperation

Colonial Office
change 5% tp on in unincorp states to 10% on lvl 3

Police coordination:
change authority on lvl 3 from 50 per lvl to 75 per lvl

Transportation:
add 5% Mapi at lvl 3

foreign investment:
increase leverage from eco dependence (need to know base value first)

**Statues:**

Military treaty
change pop growth from 2% to 1.75%
change radicals from Sol decreased from -10% to -15%

Religious convocation
change conversion rate from 25% to 100% (does way to little)

**Comment by Waysten** [comment]
note an mich :
![Image](https://github.com/user-attachments/assets/a16bc0e5-d901-4e0e-a4a9-7ed13410a3b5)

Hier die Values für neue Block Mitglieder:
![Image](https://github.com/user-attachments/assets/6e970e23-9a59-4e2c-8d34-fb77b4053449)
![Image](https://github.com/user-attachments/assets/a80b1262-5f18-484e-80e4-ecc0cb04ac06)
Hier die Berechnung für die KI 
![Image](https://github.com/user-attachments/assets/01f0d00d-0f6c-4b5a-94ae-102977b75f6e)


Das Value ist 150% das wird durch das oben gecapped. Man sollte wahrscheinlich das Cap erhöhen und dann das gain auf 2 oder 2.5 anpassen als Idee

Hier die Values für Subjects:
![Image](https://github.com/user-attachments/assets/ed1f97f6-aec0-44d7-98aa-6bd0e93e6ead)

@xEiweix 
Hoffe das kann helfen oder soll ich es erklären

**Comment by Waysten** [comment]
![Image](https://github.com/user-attachments/assets/01d2aa73-ffff-4753-a258-b1f0e6c3834a)

**Comment by xEiweix** [comment]
Jo dann am besten cap rauf

**Comment by Waysten** [comment]
wird gemacht chef
