### ISSUE TITLE
Production changes (Factories, Mines, Farms etc)

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#4]
Arbeitseinsparungs PM:
Assembly line  5 Öl + 10 Strom  (statt 10 und 5) betrifft mehrere Factories

Chemical Plant:
Leblanc Process: -15 Fertlizer ->-25Fertilizer  +20 Explosives ->+25 Explosives
Improved Fertilizer: -30 Sulfur -> -40 Sulfur   -30 Iron -> -20 Iron
Ammonia-soda Process: -15 Fertilizer -> -30 Fertilizer  +40 Explosives ->+50 Explosives
Vacuum Evaporation: -30 Fertilizer -> -45 Fertilizer   +70 Explosives -> +80 Explosives
Nitrogen Fixation prozess: -40 Sulfur -> -50 Sulfur -30 Iron -> -20 Iron
Brine Electrolysis: -50 fertilizer -> -65Fertilizer  100 Explosives -> +110Explosives

Synthetic Plant: 
Rayon: -40 Wood -> -20 Wood  -40 Dye -> -30 Dye  

Shipyards: 
Steamships:
Military Shipbuilding: -20 Steamer -> -30 Steamer  +20 Ironclads -> +30 Ironclads
Extensive Military Shipbuilding: -25 Steamer -> -45 Steamer   +25 Ironclads -> +45 Ironclads

Electrics Industries:
Radio Production: -20 Telephones -> -30 Telephones  +40 Radios -> +50 Radios

Arms Industries:
Bolt Action Rifles: -10 Oil -> -5 Oil   +75 small Arms -> +70 small Arms

Oil Rigs: 
Steam-Powered Derricks: + 60 Oil -> + 65 Oil  
Combustion Engine Derricks: +100 Oil -> +110 Oil

**Comment by MasterSon-git** [comment]
@xEiweix Assembly Line für diese beiden Gebäude ist mit: 5 Tools, 5 Oil, 5 Electricity
- pm_assembly_lines_building_furniture_manufacturies
- pm_assembly_lines_building_motor_industry

die auch ändern?

**Comment by xEiweix** [comment]
alle die die tech haben

**Comment by MasterSon-git** [comment]
und tools bei den beiden dann auf 0?

**Comment by xEiweix** [comment]
ja bitte
