### ISSUE TITLE
Infamy bracket rebalance

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#401]
**0-24.9**
no changes

**25-49.9**

**50-74.9**
add same stuff as 50-99.9 was before
add -5% inno generation

**75-99.9** (Name: Isolated)
add -10% authority
add -25% trade route comp
add -10% inno generation
add -5% gov dif eff
add +5% military goods cost

**100+**
change from -10% to -15% authority
add -15% inno generation
add -10% gov dif eff
add +10% military goods cost

**Comment by Waysten** [comment]
@MasterSon-git 
dürfen wir 00_defindes anpassen für:
75-99.9 (Name: Isolated)
ist irgendwie komisch

**Comment by MasterSon-git** [comment]
@Waysten neues Level einbauen geht nicht - dieses einfach in den defines hinzufügen wird keine Änderung im Spiel haben, da dort nur bekannte definitionen ausgewertet werden - eiwei passt den task noch an und wir schauen längerfristig ob wir ein "fake level" einbauen können

**Comment by xEiweix** [comment]
merged 50-99 und zwar mit folgenden stats

add -5% inno generation
add -15% trade route comp
