### ISSUE TITLE
Wargoals costs changes

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#43]
Protectorat wargoal: Base Value von 2 -> 1,5
Dominion wargoal:  Base Value 2
Puppet wargoal:  Base Value 2.5
Conquer State: Basevalue 5->4

**Comment by MasterSon-git** [comment]
@xEiweix Dominion und Puppet kann ich leider nicht wieder reaktivieren. Einbauen geht ohne Fehler es gibt aber keine validen Ziele für das diplo play... Darauf kann man auch leider 0 einfluss nehmen.

**Comment by MasterSon-git** [comment]
TODO: add tooltip on annex for infamy

**Comment by MasterSon-git** [comment]
TODO: AI acceptance value for annex should be significantly reduced if's not subject type puppet
