### ISSUE TITLE
Staaten Resourcen buffs

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#46]
### Österreich:
Northern Transylvania: +30 Sulfurmines
East Slovakia: +30 Iron Mines
Styria: +15 Sulfur Mines
Istria: Natural Harbors
Dalmatien: add Natural Harbors +2 Fishing Wharves
Croatien: add Natural Harbors +10 Fishing Wharves
Montenegro: add Natural Harbors +10Fishing Wharves

### Schweden: 
Svealand +10 Coal Mines 
Scania +5 Iron Mines
Northern Norway: +7 Iron Mines +5 Sulfur Mines 
### Frankreich:
Auvergne-Limousin +25 Sulfur Mines
Lorrain: +20 Coal Mines
Normandy: +20 Coal Mines
Burgundy:  +20 Coal Mines

### Italien:
Calabria: +6 Iron Mines +14 Coal Mines 
Sicily: +20 Iron Mines

### Spanien:
Navarra: +13 Kohleminen
Valencia: +20 Schwefelminen +5 Holzfäller

### Osmane:
Kastamonu: +30 Iron Mines +4 Logging Camps +15 Arable Land
Aydin: +30 Iron Mines +5 Logging Camps +12 Arable Land
Erzurum: +35 Sulfur Mines + 5 Logging Camps +5Iron Mines +10 Lead Mines
Konya: +6 Fishing Wharves +9 Logging Camps +18 Arable Land
Ankara: +20 Arable Land
Trabzon: -21 Iron Mines (Ausgleich für Kastamonu)  +12 Arable Land
Northern Thrace: +30 Coal Mines +6 Fishing Wharves
Mosul: +15 Iron Mines  +20 Arable Land
Bagdad:  +15 Arable Land
Basra: +25 Arable Land

### Niederlande:
Gelre: +20 Iron Mines

### Deutschland:
Ruhr: +5 Logging Camps +10 Iron Mines
Rhineland: +20 Iron Mines +3 Logging Camps

### Ägypten:
Lebanon +20 Iron Mines +6 Logging Camps
Palestine: +20Coal Mines +3 Logging Camps
Adana: +20 Iron Mines +15 Arable Land

### Japen:
Shikoku: +20 Coal Mines
Tohoku: +20 Coal Mines

### Mexiko:
Jalisco: +25 Coal Mines

### Brasilien:
Bahia: +5 iron Mines +20 Coal Mines
Ceara; +2 Iron Mines +15 Coal Mines

### Portugal:
Alentejo; +8 Logging Camps +6 Iron Mines +2 Coal Mines

**Comment by MasterSon-git** [comment]
TODO clarification
get errors for each changed state:
```
[08:51:20][state_region_template.cpp:1406]: (x0974E5) already defined in State Region Province Cache for the state STATE_SVEALAND.
```
