### ISSUE TITLE
"Übernahmen  Vic3 Tweakz mod"

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#47]

**Comment by xEiweix** [comment]
Vic3 Tweakz Mod:
Terrain modifier + die Dynamit Mechanic um diese zu neutralisieren

**Comment by MasterSon-git** [comment]
@xEiweix wenn ok würde ich die straits weglassen, die sind so unübersichtlich was ich da übernehmen müsste und auf was das effekte hat...

**Comment by xEiweix** [comment]
Ja keon Ding

MasterSon-git ***@***.***> schrieb am Fr., 29. Dez. 2023,
17:57:
