### ISSUE TITLE
Naval Department building

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#54]
Max lvl 5:
1PM:  875Service Men 125 Officer 2 Holz 1 Fabric  4% Navy Off / Def
2PM:  850Service Men 150 Officer 7,5 Ammo  7,5 Cannons 3 Steel 1,5 Coal    (Iron Clad tech) 6% Navy Off / Def
3PM   825Service Men 175 Officer 20 Ammo 20 Artillery 10 Radios  10 Steel 5 Coal   (Sea Lane Strategies tech) 10% Navy Off / Def

**Comment by Tziplays** [comment]
Problem ist das man State_modifiers nicht benutzen kann um eine unit in nur einem staat zu buffen es zeigt es im staat sogar an wird aber nicht auf die unit angewendet.
