### ISSUE TITLE
add decree "Public Health programm"

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#6]
+8% Birthrate
+8% Birthrate for primary cultures (falls das geht)
 -7% Mortality

(Als Icon einfach das healtcare symbol)

**Comment by MasterSon-git** [comment]
@xEiweix extra birthrate for accepted pops is no problem, for primary culture im not sure, maybe i can trigger an event to accomplish this. 

At first im adding +8% additional birthrate for accepted pops and investigate the situation for primary culture.
