### ISSUE TITLE
Land trade routes

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#71]
urbanization = 50 -> 300 LTC
urban_planning = 10 -> 100
modern_sewerage = 10 -> 100
steel_frame_buildings = 10 -> 100
elevator = 10 -> 100
paved_roads = 20 -> 200

**Comment by MasterSon-git** [comment]
- check if it's possible to add land_trade_capacity to trade routes

if it works we can check if trading partner is adjacent to current country and add more or less land_trading_capacity depending on the traded good. E.g. more for Wood less for Cars

**Comment by xEiweix** [comment]
Adjacent passiert sobald du irgendwelche Grenzen zwischen den Märkten
teilst mit Marktführer oder Teilnehmern

Idealerweise wurde die capacity halt bei Gütern unterscheiden

MasterSon-git ***@***.***> schrieb am Mi., 3. Jan. 2024,
12:42:
