### ISSUE TITLE
Cornlaw rebalance

### ISSUE THREAD

**Issue by xEiweix** [MasterSon-git/vic3-kmpmp#76]
Condition change 25% grain price -> 20% 

check meantime for pulse event

**Comment by MasterSon-git** [comment]
@xEiweix monatlich tritt mit einer wahrscheinlichkeit von 13% eines der corn law events auf

**Comment by MasterSon-git** [comment]
@xEiweix ähh moment ich bin schlecht in mathe ^^
```
	on_monthly_pulse = {
		random_events = {
			100 = 0
			10 = corn_laws.2
			10 = corn_laws.3
			10 = corn_laws.4
		}
	}
```

das sind 30/100 * 100 = 30% Wahrscheinlichkeit, dass eines der Ereignisse auftritt oder?

**Comment by MasterSon-git** [comment]
raised chance for modern conservative event from 7% to 14%
